version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    env_file:
      - ./mariadb.env

    volumes:
      - mariadb-data:/var/lib/mysql
      - ./scripts/database_tables.sql:/docker-entrypoint-initdb.d/database_tables.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  fastapi-app:
    build:
      context: ..
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    env_file:
      - docker.env
    depends_on:
      - mariadb
    restart: unless-stopped

volumes:
  mariadb-data:
